Repository See-Rex/see-rex, pull requests merged in 2022-09, with the labels that each got.

#7 [Feature][Merv] Add Icon Button
  components/Icon_Button/_index.module.scss
  components/Icon_Button/index.tsx
  pages/index.tsx
  public/residential.svg
Labels: feature

#8 [Feature][Merv] Add basic footer
  components/Basic_Footer/_index.module.scss
  components/Basic_Footer/index.tsx
  pages/index.tsx
Labels: feature

#9 [Feature][Taps] Added Hero Banner and Optimized some code
  components/BasicHeader/_index.module.scss
  components/BasicHeader/index.tsx
  components/Basic_Header/index.tsx
  components/LandingBanner/_index.module.scss
  components/LandingBanner/index.tsx
  components/PassField/_index.module.scss
  components/PassField/index.tsx
  components/StyledButton/_index.module.scss
  components/StyledButton/index.tsx
  components/Styled_Button/index.tsx
  components/TextField/_index.module.scss
  components/TextField/index.tsx
  components/index.tsx
  pages/index.tsx
  public/Icon/index.tsx
  public/background1.png
  public/favicon.ico
  public/vercel.svg
  styles/_constants.scss
  styles/_text.scss
Labels: feature

#12 [Adjustments][Taps] Revamped Code Conventions
  components/BasicHeader/_index.module.scss
  components/BasicHeader/index.tsx
  components/InputField/_index.module.scss
  components/InputField/index.tsx
  components/PassField/index.tsx
  components/StyledButton/_index.module.scss
  components/StyledButton/index.tsx
  components/TextField/_index.module.scss
  components/TextField/index.tsx
  components/index.tsx
  package-lock.json
  pages/index.tsx
  public/Icon/index.tsx
Labels: adjustments

#13 [Feature][Jez] Added type definitions for expected props
  typings.d.tsx
Labels: feature

#15 [Misc][Tapayan] Optimization of Styling and Resizing Features
  components/BasicFooter/_index.module.scss
  components/BasicHeader/_index.module.scss
  components/BasicHeader/index.tsx
  components/IconButton/_index.module.scss
  components/IconButton/index.tsx
  components/LandingBanner/_index.module.scss
  components/StyledButton/_index.module.scss
  components/StyledButton/index.tsx
  pages/index.tsx
  public/Icon/_index.module.scss
  public/Icon/index.tsx
  styles/_constants.scss
  styles/_theme.scss
Labels: misc

#18 [Misc][Tapayan] Added Missing Icons
  public/Icons/IconLogout.tsx
  public/Icons/IconSpaceDashboard.tsx
Labels: misc

#19 [Adjustment][Tapayan] Added Missing Color Change for Dashboard Icon
  components/CollapsedBar/index.tsx
  public/Icons/IconSpaceDashboard.tsx
  public/Icons/index.ts
Labels: adjustments

#20 [Misc][Tapayan] Final Changes in Collapsed Navigation Bar
  components/CollapsedBar/index.tsx
  components/IconButton/_index.module.scss
  components/IconButton/index.tsx
  components/index.ts
Labels: misc

#22 [Feature][Tapayan] Admin Layout Finished
  components/BasicFooter/_index.module.scss
  components/BasicFooter/index.tsx
  components/BasicHeader/_index.module.scss
  components/BasicHeader/index.tsx
  components/CollapsedBar/_index.module.scss
  components/CollapsedBar/index.tsx
  components/IconButton/_index.module.scss
  components/IconButton/index.tsx
  components/StyledButton/_index.module.scss
  components/StyledButton/index.tsx
  components/index.ts
  layouts/AdminLayout/index.tsx
  pages/_app.tsx
  pages/dashboard/index.tsx
  pages/index.tsx
  pages/storypage.tsx
  public/Icons/IconContacts.tsx
  public/Icons/IconHolidayVillage.tsx
  public/Icons/IconLandscape.tsx
  public/Icons/IconLocationCity.tsx
  public/Icons/IconLogout.tsx
  public/Icons/IconSpaceDashboard.tsx
  public/Icons/_index.module.scss
  public/Logo/index.tsx
  styles/_home.module.scss
Labels: feature

#21 [Feature][Merv] Add google button & sign-in/register layout
  components/CollapsedBar/index.tsx
  components/GoogleButton/index.tsx
  components/IconButton/_index.module.scss
  components/IconButton/index.tsx
  components/InputField/index.tsx
  components/StyledButton/index.tsx
  components/TextField/index.tsx
  components/index.ts
  layouts/AdminLayout/index.tsx
  layouts/AuthLayout/_index.module.scss
  layouts/AuthLayout/index.tsx
  pages/auth/index.tsx
  pages/index.tsx
  pages/storypage.tsx
  public/Icons/ArrowBack.tsx
  public/Icons/index.ts
Labels: feature

#23 [Feature][Merv] Add Progress Stat Card
  components/ProgressStatCard/_index.module.scss
  components/ProgressStatCard/index.tsx
  pages/test/index.tsx
  styles/_constants.scss
Labels: feature

#24 [Feature][Merv] Added Grid Stat Card
  components/ProgressStatCard/index.tsx
  components/StatisticCard/_index.module.scss
  components/StatisticCard/index.tsx
  pages/test/index.tsx
Labels: feature

#26 [Feature][Merv] Added Group Statistic Card
  components/CollapsedBar/index.tsx
  components/InputField/index.tsx
  components/ProtectedRoute/index.tsx
  components/StatisticCard/_index.module.scss
  components/StatisticCard/index.tsx
  components/StyledButton/index.tsx
  components/TextField/index.tsx
  config/firebase.ts
  context/AuthContext.tsx
  layouts/AuthLayout/index.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/auth/_index.module.scss
  pages/auth/index.tsx
  pages/auth/login.tsx
  pages/auth/register.tsx
  pages/auth/resetpassword.tsx
  pages/storypage.tsx
  pages/test/index.tsx
Labels: feature

#27 [Misc][Tapayan]Minor Adjustments in Collapsed Bar
  components/CollapsedBar/index.tsx
Labels: misc

#28 [Adjustments][Tapayan] Optimized Implementation of Input Fields
  components/InputField/index.tsx
  components/TextField/index.tsx
  pages/auth/login.tsx
  pages/auth/register.tsx
  pages/storypage.tsx
Labels: adjustments

#29 [Adjustments][Tapayan] Progress Statistic Card Revamp
  components/ProgressCard/_index.module.scss
  components/ProgressCard/index.tsx
  pages/storypage.tsx
Labels: adjustments

#32 [Adjustments][Tapayan] Theming Adjustments
  components/CollapsedBar/index.tsx
  components/GroupCard/_index.module.scss
  components/GroupCard/index.tsx
Labels: adjustments

#33 [Adjustments][Merv] Make Auth Layouts Adaptive
  components/BasicFooter/index.tsx
  components/InputField/_index.module.scss
  components/InputField/index.tsx
  layouts/AuthLayout/_index.module.scss
  layouts/AuthLayout/index.tsx
  pages/auth/_index.module.scss
  pages/auth/login.tsx
  pages/auth/register.tsx
  pages/auth/resetpassword.tsx
Labels: adjustments

#35 [Feature][Merv] Add reset password functionality
  context/AuthContext.tsx
  pages/auth/resetpassword.tsx
Labels: feature

#36 [Feature][Tapayan] FeatureCard Component
  components/FeatureCard/_index.module.scss
  components/FeatureCard/index.tsx
  pages/storypage.tsx
Labels: feature

#39 [Feature][Merv] Main footer initial
  components/MainFooter/_index.module.scss
  components/MainFooter/index.tsx
  pages/storypage.tsx
Labels: fix

#40 [Adjustments][Tapayan] Changed Icons to Emphasize Variety
  components/FeatureHero/index.tsx
Labels: adjustments

#43 [Adjustments][Merv] Adjust auth layout page container for whole page
  components/MainFooter/_index.module.scss
  layouts/AuthLayout/_index.module.scss
  layouts/AuthLayout/index.tsx
  pages/auth/_index.module.scss
  pages/auth/login.tsx
Labels: adjustments

#44 [Misc][Tapayan] Proper Component Indexing and Importation
  components/FeatureHero/index.tsx
  components/LandingBanner/index.tsx
  components/StyledButton/index.tsx
  components/index.ts
  pages/storypage.tsx
Labels: misc

#45 [Fix][Tapayan] Minor Fix in Main Footer Theming
  components/MainFooter/_index.module.scss
  components/MainFooter/index.tsx
Labels: fix

#47 [Adjustments][Tapayan] Dark Theme Changes
  components/GroupCard/_index.module.scss
  components/IconButton/_index.module.scss
  components/MainFooter/_index.module.scss
  components/StyledButton/_index.module.scss
  pages/storypage.tsx
  styles/_constants.scss
  styles/global.scss
Labels: adjustments

#48 [Misc][Tapayan] AppCard Changes
  components/AppCard/_index.module.scss
  components/AppCard/index.tsx
Labels: misc

#49 [Adjustments][Tapayan] Minor Theming Changes
  components/AppCard/_index.module.scss
  components/AppCard/index.tsx
  components/StyledButton/_index.module.scss
  components/StyledButton/index.tsx
Labels: adjustments

#50 [Feature][Tapayan] StoryPage Component Highlight Init
  components/AppCard/index.tsx
  components/StyledButton/_index.module.scss
  components/StyledButton/index.tsx
  pages/devhandout.tsx
  pages/index.tsx
  pages/storypage/index.tsx
  styles/_constants.scss
  styles/_text.scss
Labels: feature

#53 [Adjustments][Tapayan] Hover Changes in Card Buttons
  components/AppCard/_index.module.scss
  components/AppCard/index.tsx
  components/StyledButton/_index.module.scss
  components/StyledButton/index.tsx
Labels: adjustments

#55 [Adjustments][Tapayan] Styling Fixes in IconButton Component
  components/IconButton/_index.module.scss
  components/IconButton/index.tsx
Labels: adjustments

#56 [Feature][Tapayan] Color Toggle Component
  components/ColorToggle/index.tsx
  pages/_app.tsx
Labels: feature

#57 [Feature][Merv] Add error 404 page
  pages/404.tsx
  pages/_app.tsx
  routes/ProtectedRoute/index.tsx
Labels: feature

#60 [Adjustments][Tapayan] Additional Type for Styled Button
  components/StyledButton/_index.module.scss
  components/StyledButton/index.tsx
Labels: adjustments

#61 [Feature][Tapayan] Added Story Page
  components/StoryBar/index.tsx
  layouts/StoryLayout/_index.module.scss
  layouts/StoryLayout/index.tsx
  pages/dev/index.tsx
  pages/index.tsx
  pages/story/index.tsx
  pages/storypage/index.tsx
Labels: feature

#62 [Adjustments][Tapayan] Responsiveness and Styling Changes for Components
  components/BasicFooter/_index.module.scss
  components/InputField/index.tsx
  components/ProgressCard/index.tsx
  components/StatisticCard/index.tsx
  components/index.ts
Labels: adjustments

#63 [Fix][Tapayan] Burger Button Theming Bug Fix
  components/BasicHeader/_index.module.scss
  components/BasicHeader/index.tsx
Labels: fix

#64 [Fix][Merv] Remove auth index to fix build
  pages/auth/index.tsx
  pages/test/index.tsx
Labels: fix
