Repository See-Rex/see-rex, pull requests merged in 2022-10, with the labels that each got.

#65 [Adjustment][Merv] Add linting rules and Authlayout app shell
  .eslintrc.json
  .prettierrc
  components/AppCard/index.tsx
  components/BasicHeader/index.tsx
  components/CollapsedBar/index.tsx
  components/ColorToggle/index.tsx
  components/FeatureHero/index.tsx
  components/GoogleButton/index.tsx
  components/GroupCard/index.tsx
  components/IconButton/index.tsx
  components/InputField/index.tsx
  components/LandingBanner/index.tsx
  components/ProgressCard/index.tsx
  components/StoryBar/index.tsx
  components/StyledButton/index.tsx
  layouts/AdminLayout/index.tsx
  layouts/AuthLayout/_index.module.scss
  layouts/AuthLayout/index.tsx
  layouts/StoryLayout/index.tsx
  package-lock.json
  package.json
  pages/404.tsx
  pages/_app.tsx
  pages/_index.module.scss
  pages/auth/_index.module.scss
  pages/auth/login.tsx
  pages/auth/register.tsx
  pages/auth/resetpassword.tsx
  pages/dev/index.tsx
  pages/story/index.tsx
Labels: adjustments

#68 [Fix][Tapayan] Basic Header Alignment Fix
  components/BasicHeader/index.tsx
Labels: fix

#69 [Misc][Tapayan] Admin Dashboard Homepage Optimization
  layouts/AdminLayout/index.tsx
  layouts/StoryLayout/index.tsx
  pagination/Homepage/index.tsx
Labels: misc

#71 [Adjustments][Tapayan] Linter Induced Changes
  components/AppCard/_index.module.scss
  components/BasicHeader/index.tsx
  components/CollapsedBar/index.tsx
  components/GoogleButton/index.tsx
  hooks/AuthContext.tsx
  pages/_app.tsx
  pages/auth/login.tsx
  pages/auth/register.tsx
  pages/auth/resetpassword.tsx
  routes/ProtectedRoute/index.tsx
Labels: adjustments

#72 [Adjustments][Tapayan] Table Theming Minor Change
  components/ContactsTable/_index.module.scss
Labels: adjustments

#75 [Feature][Tapayan] Landing Page
  components/LandingBanner/index.tsx
  layouts/LandingLayout/index.tsx
  pages/index.tsx
Labels: feature

#76 [Feature][Merv] Add residential properties page
  components/AppCard/_index.module.scss
  components/AppCard/index.tsx
  components/CollapsedBar/index.tsx
  components/SegmentedToggle/index.tsx
  pages/dashboard/index.tsx
  pages/dev/index.tsx
  pages/story/index.tsx
  pagination/ResidentialProperties/_index.module.scss
  pagination/ResidentialProperties/index.tsx
  pseudodata.ts
Labels: feature

#81 [Feature][Merv] Add filter picker component
  components/FilterPicker/_index.module.scss
  components/FilterPicker/index.tsx
  components/Search/_index.module.scss
  components/Search/index.tsx
  components/index.ts
  enums/PropertyInfo.enum.ts
  hooks/PropertyContext.tsx
  pages/dev/index.tsx
  pagination/LandProperties/index.tsx
  pagination/NonResidentialProperties/index.tsx
  pagination/ResidentialProperties/index.tsx
  pseudodata.ts
  public/Icons/index.ts
Labels: feature

#86 [Adjustment][Floreta] Update sanity configs and dependencies
  package-lock.json
  package.json
  sanity.js
  sanity.tsx
  tsconfig.json
  typings.d.tsx
Labels: adjustments

#82 [Feature][Tapayan] Added Feature Hero in Main Landing Page
  components/FeatureHero/index.tsx
  layouts/LandingLayout/index.tsx
Labels: feature

#83 [Adjustments][Tapayan] Changed Table Features
  components/ContactsTable/index.tsx
  pagination/Contacts/index.tsx
  pseudodata.ts
Labels: adjustments

#88 [Feature][Floreta]Add dynamic page setup for vehicles
  pages/vehicle/[slug].tsx
  see-rex-superadmin/node_modules/.cache/babel-loader/d81307658b5e69f2855f0f67aa1d27a2.json.gz
  typings.d.tsx
Labels: feature

#89 [Feature][Floreta] create file for residential properties
  pages/residential-property/[slug].tsx
Labels: feature

#91 [Feature][Floreta] create file for nonresidential properties
  pages/nonresidential-property/[slug].tsx
  see-rex-superadmin/node_modules/.cache/babel-loader/18dba5bab269c9098599e6c96312dd0f.json.gz
  see-rex-superadmin/node_modules/.cache/babel-loader/6ad94417c1277b3296620af013a8259a.json.gz
  see-rex-superadmin/node_modules/.cache/babel-loader/cce66217cc75402bdac50287ce3a815e.json.gz
  see-rex-superadmin/schemas/land.js
  see-rex-superadmin/schemas/nonResidentialProperty.js
  see-rex-superadmin/schemas/schema.js
Labels: feature

#93 [Feature][Tapayan] Contact Form Modal
  components/ContactForm/_index.module.scss
  components/ContactForm/index.tsx
  components/ContactIconList/index.tsx
  components/ContactUsForm/index.tsx
  components/ContactsTable/index.tsx
  components/TextArea/_index.module.scss
  components/index.ts
  pseudodata.ts
Labels: feature

#94 [Adjustments][Tapayan] Property Lists Optimizations
  components/AppCard/_index.module.scss
  components/FilterPicker/_index.module.scss
  components/FilterPicker/index.tsx
  components/Search/_index.module.scss
  pagination/LandProperties/index.tsx
  pagination/NonResidentialProperties/index.tsx
  pagination/ResidentialProperties/index.tsx
Labels: adjustments

#96 [Adjustments][Tapayan] Contact Form Optimizations
  components/ContactForm/_index.module.scss
  components/ContactForm/index.tsx
  components/ContactUsForm/index.tsx
  components/TextArea/index.tsx
Labels: adjustments

#98 [Fix][Merv] Fix google sign in with try catch
  hooks/AuthContext.tsx
Labels: fix

#101 [Adjustments][Tapayan] Replaced Navbar with Drawer in Mobile
  components/CollapsedBar/_index.module.scss
  components/CollapsedBar/index.tsx
  components/ContactsTable/index.tsx
  components/StoryBar/_index.module.scss
  components/StoryBar/index.tsx
  pages/dev/index.tsx
Labels: adjustments

#102 [Feature][Tapayan] Landing Page Redesign
  components/LandingHeader/_index.module.scss
  components/LandingHeader/index.tsx
  components/MainFooter/_index.module.scss
  components/StyledButton/_index.module.scss
  components/StyledButton/index.tsx
  components/index.ts
  layouts/LandingLayout/_index.module.scss
  layouts/LandingLayout/index.tsx
  package-lock.json
  package.json
Labels: feature

#103 [Feature][Merv] Add toast alert
  components/CollapsedBar/index.tsx
  components/ContactForm/index.tsx
  components/FeatureHero/index.tsx
  components/GoogleButton/index.tsx
  components/Search/index.tsx
  components/SeeRexAlert/index.tsx
  components/index.ts
  hooks/AuthContext.tsx
  layouts/AuthLayout/_index.module.scss
  package-lock.json
  package.json
  pages/_app.tsx
  pages/auth/index.tsx
  pages/auth/login.tsx
  pages/auth/register.tsx
  pages/auth/resetpassword.tsx
  pages/dev/index.tsx
  pages/nonresidential-property/[slug].tsx
  pages/residential-property/[slug].tsx
  pages/vehicle/[slug].tsx
  routes/ProtectedRoute/index.tsx
Labels: feature

#106 [Feature][Tapayan] Animated SeeRex Loading Screen
  components/SeeRexLoader/index.tsx
  hooks/PropertyContext.tsx
  next.config.js
  package-lock.json
  package.json
  pages/auth/index.tsx
  public/AnimatedBg.svg
  public/BgAnimated.svg
  public/LoadingDark.svg
  public/LoadingLight.svg
Labels: feature

#107 [Feature][Tapayan] Landing Page Redesign with Carousel
  components/MainHeader/_index.module.scss
  components/MainHeader/index.tsx
  components/index.ts
  layouts/LandingLayout/_index.module.scss
  layouts/LandingLayout/index.tsx
  styles/_constants.scss
  styles/_text.scss
  styles/global.scss
Labels: feature

#108 [Misc][Tapayan] Admin Contacts Page Adjusments
  components/ContactForm/_index.module.scss
  components/ContactForm/index.tsx
  components/ContactIcon/_index.module.scss
  components/ContactIcon/index.tsx
  components/ContactIconList/index.tsx
  components/ContactInfo/_index.module.scss
  components/ContactInfo/index.tsx
  components/ContactUsForm/index.tsx
  components/ContactsTable/_index.module.scss
  components/ContactsTable/index.tsx
  components/index.ts
Labels: misc

#110 [Adjustment][Merv] Logged In/Authenticated users reroute to dashboard
  .gitignore
  pages/index.tsx
Labels: adjustments

#104 [Feature][Floreta] add server data fetching to residential property
  pages/dashboard/index.tsx
  pagination/ResidentialProperties/index.tsx
Labels: feature

#114 [Feature][Floreta] Add Image Slide Document Type for Image Carousel
  next.config.js
  package-lock.json
  package.json
  pages/residential-property/[slug].tsx
  pages/residential-property/_index.module.scss
  pagination/ResidentialProperties/index.tsx
  see-rex-superadmin/schemas/imageSlides.js
  see-rex-superadmin/schemas/land.js
  see-rex-superadmin/schemas/nonResidentialProperty.js
  see-rex-superadmin/schemas/property.js
  see-rex-superadmin/schemas/schema.js
  typings.d.tsx
Labels: feature

#115 [Feature][Merv] Add property detail page
  pages/residential-property/[slug].tsx
  pages/residential-property/_index.module.scss
  typings.d.tsx
Labels: feature

#116 [Adjustment][Floreta] Update on sanity studio files upon rebuild
  see-rex-superadmin/dist/index.html
  see-rex-superadmin/dist/static/.gitkeep
  see-rex-superadmin/dist/static/css/main.css
  see-rex-superadmin/dist/static/favicon.ico
  see-rex-superadmin/dist/static/js/app.bundle.js
  see-rex-superadmin/dist/static/js/vendor.bundle.js
Labels: adjustments

#117 [Adjustment][Floreta] Added new fields to property for filtering
  see-rex-superadmin/schemas/property.js
Labels: adjustments

#118 [Adjustment][Floreta] Added area field
  see-rex-superadmin/schemas/property.js
Labels: adjustments

#122 [Feature][Tapayan] Landing Page Redesign
  components/FeatureCard/_index.module.scss
  components/FeatureCard/index.tsx
  layouts/LandingLayout/_index.module.scss
  layouts/LandingLayout/index.tsx
  package-lock.json
  package.json
  public/handBackdrop.png
  public/last-bg.png
  public/page2bg.png
  public/page3bg.jpg
Labels: feature
